### ISSUE TITLE
Generating Multiple Outputs Per Prompt Triggers Out-of-Memory (OOM) Error

### ISSUE THREAD

**Issue by jchan58** [pat-jj/DeepRetrieval#34]
Hi, when I try to generate 5 outputs per prompt—by setting `actor_rollout_ref.rollout.n=5` in ctgov.sh during training—I always run into GPU out-of-memory (OOM) errors. I’ve tried lowering the batch size and even reduced `actor_rollout_ref.rollout.n` to 2, but I still get OOM errors.

Is there any way around this?

**Comment by pat-jj** [comment]
Hi! Could you share your full .sh script and your device information?

**Comment by jchan58** [comment]
Sure, this is the script and I am using a H200 GPU

 `export CUDA_VISIBLE_DEVICES=0

DATE=$(date '+%Y-%m-%d-%H-%M-%S')

python3 -m verl.trainer.main_ppo \
    data.train_files=data/search_engine/ctgov/train.parquet \
    data.val_files=data/search_engine/ctgov/test.parquet \
    data.train_batch_size=16 \
    data.val_batch_size=16 \
    data.max_prompt_length=2048 \
    data.max_response_length=2048 \
    actor_rollout_ref.actor.optim.lr=1e-6 \
    actor_rollout_ref.actor.strategy=fsdp \
    actor_rollout_ref.actor.ppo_mini_batch_size=8 \
    actor_rollout_ref.actor.ppo_micro_batch_size=4 \
    actor_rollout_ref.rollout.n=5 \
    critic.ppo_micro_batch_size=8 \
    actor_rollout_ref.rollout.log_prob_micro_batch_size=1 \
    actor_rollout_ref.rollout.temperature=0.6 \
    actor_rollout_ref.rollout.tensor_model_parallel_size=1 \
    actor_rollout_ref.rollout.gpu_memory_utilization=0.2 \
    actor_rollout_ref.ref.log_prob_micro_batch_size=2 \
    actor_rollout_ref.model.enable_gradient_checkpointing=True \
    actor_rollout_ref.ref.fsdp_config.param_offload=True \
    critic.model.enable_gradient_checkpointing=True \
    critic.optim.lr=1e-5 \
    algorithm.kl_ctrl.kl_coef=0.001 \
    trainer.logger=[] \
    +trainer.val_before_train=False \
    trainer.default_hdfs_dir=null \
    trainer.n_gpus_per_node=1 \
    trainer.nnodes=1 \
    trainer.save_freq=2 \
    trainer.test_freq=2 \
    trainer.project_name=ctgov2.5 \
    trainer.experiment_name=ctgov2.5 \
    actor_rollout_ref.model.path=/netmnt/vast01/cbb01/lulab/joeychan/hf_cache/hub/models--Qwen--Qwen2.5-3B-Instruct/snapshots/aa8e72537993ba99e69dfaafa59ed015b17504d1 \
    critic.model.path=/netmnt/vast01/cbb01/lulab/joeychan/hf_cache/hub/models--Qwen--Qwen2.5-3B-Instruct/snapshots/aa8e72537993ba99e69dfaafa59ed015b17504d1 \
    trainer.default_local_dir=/netmnt/vast01/cbb01/lulab/joeychan/DeepRetrieval/checkpoints/ctgov2.5 \
    trainer.total_epochs=10 | tee exp_log/32-ppo-verl_demo_$DATE.log `

**Comment by pat-jj** [comment]
Thanks! I believe both `data.max_prompt_length` and `data.max_response_length` are set too high (2048), which likely contributes significantly to the OOM issue. In our case, we set them as 500.

**Comment by jchan58** [comment]
I changed to 500 but still get the OOM issue.

**Comment by jchan58** [comment]
That fixed it! That's bring up another question - how can I resume training from a certain step if the training suddenly crashes? I know there are global_steps, but it always seems to start back at step 0.

**Comment by pat-jj** [comment]
Great! You can resume training from a saved checkpoint by specifying the following in your script:

```
    actor_rollout_ref.model.path=[your saved "actor" checkpoint] \
    critic.model.path=[your saved "critic" checkpoint] \
```
However, note that this doesn't precisely resume training from the exact previous step. This limitation comes from the current version of VERL we’re using. Still, the resumed training should behave similarly.

**Comment by jchan58** [comment]
@pat-jj thanks for the comment. So I changed what you mentioned above to this
`actor_rollout_ref.model.path=/netmnt/vast01/cbb01/lulab/joeychan/DeepRetrieval/checkpoints/ctgov2.5_2nd/actor/global_step_4 \
    critic.model.path=/netmnt/vast01/cbb01/lulab/joeychan/DeepRetrieval/checkpoints/ctgov2.5_2nd/critic/global_step_4 \`

however my exp_log seems to say that it starts from epoch 0, step 1 when I run the train script

**Comment by pat-jj** [comment]
@jchan58 Yes, that’s expected. The resume functionality is somewhat limited—it loads the checkpoint and continues training from epoch 0, step 1. While not a perfect continuation, it generally works well for most cases.

**Comment by pat-jj** [comment]
Hi Joey, BTW, I also recommend training the PubMed model first, as it transfers well to ClinicalTrials.gov. You can also fine-tune the ClinicalTrials.gov model on top of the pre-trained PubMed model for stronger performance.

**Comment by jchan58** [comment]
Hi Patrick, thanks for the advice. I would train the PubMed model first, but we have a different prompt than what the original DeepRetrieval code is using as we are asking the model to generate up to 32 keywords base on the patient's notes/summary (this is based on TrialGPT's keyword generation prompt). So, I'm not sure if training the PubMed model would help in this case, as it seems like you pass the PICO format to the model and output a boolean query.

**Comment by pat-jj** [comment]
I see. Sure, I believe PubMed will still help as the input-output formats of our pubmed and clinicaltrials.gov datasets are mostly the same!

**Comment by jchan58** [comment]
Ok, I think that makes sense since the formatting is still the same ie extracting the results from <answer> .....</answer>. I'll give it a try - thanks for the suggestion.
